strydercorp/documentation

csv.rst

Reformatting and adding lots of information.

Reformatted the user.csv file to include links to example files.

---

csv.rst

Added information on how to to transition students from undergrads to alumni

Updated CSV file

---

application_interview_schedules.rst
application_labels.rst
application_mass_emails.rst
application_mentorships.rst
application_notifications.rst
application_payments.rst
application_posts.rst
application_qualifications.rst
application_student_permissions.rst
application_users.rst

This time for the second half of the docs in alphabetical order

More typos and editing

---

api.rst
application_users.rst
csv.rst

https://github.com/strydercorp/handshake/pull/2371/files

work on listing new attributes. show deprecated attributes

---

email_delivery.rst
index.rst

adding email deliverly v0

---

references.rst

Adding the available permissions to the documentation

Add Permissions

---

references.rst

The format was not right. Fixing that.

Updating permissions formatting

---

csv.rst
data_transfer.rst

Removed jobs from cvs upload, removed disabling alumni option, removed /test from users documentation and added work auth fields.

Removed Jobs from CSV Upload, removed disabling alumni, removed /test

---

csv.rst
data_transfer.rst

12/8/2015 Updates

---

sso.rst

add whitelisting info to docs

---

csv.rst

fixed education level name and removed confusing disabling sync note

education-level-name fix

---

csv.rst

Added file requirements for CSV uploads (formatting, encoding, etc)
Updated middle name text

updates to csv doc

---

api.rst

Put in stronger language around API Token safeguarding.
inspired by: https://labs.detectify.com/2016/04/28/slack-bot-token-leakage-exposing-business-critical-information/

Stronger API token safeguarding language

---

csv.rst

specify first name requirement to prevent confusion when uploading new students

Specify first name requirement

---

csv.rst

Add warnings + requirements for staff upload

Update staff requirements and recommendations

---

csv.rst

Fixed staff formatting issues that caused breaks + resolve minor
warnings found in restive

fix-formatting-issues

---

api.rst
application_mass_emails.rst

mass email warning update

---

csv.rst

updating identifiable ID for notes and labels to clarify type and use case

Teena update doc

---

index.rst

note: unable to properly test in restview, may need to fix tech doc after merge

should hide API from table

---

csv.rst

read title
